-- v6 Phase 8: plugin attribution on Kafka envelopes. Gateway stamps
-- the validated session JWT's `plugin_id` claim into the Avro v2
-- envelope for both portfolio_events.v2 and data.v2. RW's Kafka source
-- tables get a matching column so downstream queries (notably the
-- self-service plugin uninstall path) can filter
--   WHERE org_id=$1 AND plugin_id=$2
-- to enumerate every key the plugin produced and tombstone them.
--
-- Records that predate this migration land with NULL plugin_id; they
-- won't be tombstoned by uninstall. Documented limitation in
-- ADR-0050 (self-service plugin management).
--
-- The `plugin_id` column now lives in the Phase-A baseline definition of
-- both source tables (01-sources/{data_log,portfolio_events_log}.sql) so a
-- cold rebuild creates it before the Phase-A views that read it
-- (ohlcv_coverage). This migration is retained as a recorded no-op: warm
-- DBs that already applied the ALTERs keep their column; a fresh DB gets it
-- from the baseline and skips the (now redundant) ALTERs here. RisingWave
-- has no ADD COLUMN IF NOT EXISTS, so leaving the ALTERs would double-add
-- on cold start.
SELECT 1;
